name = "ip-lookup"
main = "src/index.ts"
compatibility_date = "2022-11-05"

workers_dev = false
route = { pattern = "ip.frog.lol/*", zone_name = "frog.lol" }

kv_namespaces = [
	 { binding = "IP2NETWORK", id = "f15b1c724073431e9aff0f6e0ba23bfa", preview_id = "f15b1c724073431e9aff0f6e0ba23bfa" }
]
