name = "ip-frog-lol"
main = "src/index.ts"
compatibility_date = "2022-11-05"

workers_dev = false
route = { pattern = "ip.frog.lol/*", zone_name = "frog.lol" }

kv_namespaces = [
	 { binding = "IP2NETWORK", id = "3d4ab5e75c5149348c50c19600322c0c", preview_id = "3d4ab5e75c5149348c50c19600322c0c" }
]
